version: '3.8'

services:
  ansible:
    build:
      context: .
      dockerfile: Dockerfile
    image: ansible_docker:secure
    container_name: ansible_secure
    hostname: ansible-controller
    
    # Security configurations
    security_opt:
      - no-new-privileges:true
      - apparmor:docker-default
    
    # Drop all capabilities and only add what's needed
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
      - DAC_OVERRIDE
    
    # Resource limits
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 512M
    
    # Read-only root filesystem with specific writable directories
    read_only: true
    tmpfs:
      - /tmp:noexec,nosuid,size=100M
      - /run:noexec,nosuid,size=10M
      - /home/ansible/.ansible/tmp:noexec,nosuid,size=100M
    
    # Volumes for persistent data and SSH keys
    volumes:
      # Mount SSH keys from host (read-only)
      - ~/.ssh:/home/ansible/.ssh:ro
      # Ansible workspace
      - ./ansible_workspace:/install/ansible:rw
      # Ansible configuration
      - ./ansible.cfg:/home/ansible/.ansible.cfg:ro
      # Known hosts file
      - ./known_hosts:/home/ansible/.ssh/known_hosts:ro
    
    # Network configuration
    networks:
      - ansible_network
    
    # Environment variables
    environment:
      - ANSIBLE_HOST_KEY_CHECKING=True
      - ANSIBLE_RETRY_FILES_ENABLED=False
      - ANSIBLE_NOCOWS=1
      - ANSIBLE_GATHERING=smart
      - ANSIBLE_FACT_CACHING=jsonfile
      - ANSIBLE_FACT_CACHING_CONNECTION=/tmp/ansible_facts
      - ANSIBLE_FACT_CACHING_TIMEOUT=3600
      - PYTHONDONTWRITEBYTECODE=1
    
    # Health check
    healthcheck:
      test: ["CMD", "ansible", "--version"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # Restart policy
    restart: unless-stopped
    
    # User to run as (non-root)
    user: ansible
    
    # Disable stdin
    stdin_open: false
    tty: false

networks:
  ansible_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
    driver_opts:
      com.docker.network.bridge.name: br_ansible